config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root 'home#index'

  resources :events do
    member do
      post 'invite'
      get 'join'
      get 'details'
      get 'invite'
      get 'polls'
      get 'comments'
      get 'announcements'
    end
    resources :polls, only: [:create, :destroy] do
      resources :poll_options, only: [:new, :create, :edit, :update, :destroy] do
        resources :votes, only: [:create, :destroy]
      end
    end
    resources :comments, only: [:create, :update] do
      member do
        patch 'pin'
      end
    end
  end

  resources :users, only: [:show]
end

app/models/poll_option.rb
class PollOption < ApplicationRecord
  belongs_to :poll
  has_many :votes, dependent: :destroy

  validates :title, presence: true
end

app/controllers/poll_options_controller.rb
class PollOptionsController < ApplicationController
  before_action :set_event_and_poll
  before_action :authorize_user!

  def new
    @poll_option = @poll.poll_options.build
  end

  def create
    @poll_option = @poll.poll_options.build(poll_option_params)
    if @poll_option.save
      redirect_to @event, notice: 'Poll option was successfully created.'
    else
      render :new
    end
  end

  def edit
    @poll_option = @poll.poll_options.find(params[:id])
  end

  def update
    @poll_option = @poll.poll_options.find(params[:id])
    if @poll_option.update(poll_option_params)
      redirect_to @event, notice: 'Poll option was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @poll_option = @poll.poll_options.find(params[:id])
    @poll_option.destroy
    redirect_to @event, notice: 'Poll option was successfully deleted.'
  end

  private

  def set_event_and_poll
    @event = Event.find(params[:event_id])
    @poll = Poll.find(params[:poll_id])
  end

  def authorize_user!
    unless @event.creator == current_user || @event.attendees.exists?(id: current_user.id)
      redirect_to events_path, alert: 'You are not authorized to perform this action.'
    end
  end

  def poll_option_params
    params.require(:poll_option).permit(:title)
  end
end

app/helpers/poll_options_helper.rb
module PollOptionsHelper
end

app/views/poll_options/edit.html.erb
<h1>Edit Poll Option</h1>

<%= form_with(model: [@event, @poll, @poll_option], local: true) do |form| %>
  <% if @poll_option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll_option.errors.count, "error") %> prohibited this poll option from being saved:</h2>
      <ul>
        <% @poll_option.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit 'Update Poll Option', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/poll_options/new.html.erb
<h1>Add a Poll Option</h1>

<%= form_with(model: [@event, @poll, @poll_option], local: true) do |form| %>
  <% if @poll_option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll_option.errors.count, "error") %> prohibited this poll option from being saved:</h2>
      <ul>
        <% @poll_option.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit "Create Poll Option" %>
  </div>
<% end %>

app/views/poll_options/show.html.erb
<ul class="list-group list-group-flush">
  <% total_votes = poll.poll_options.sum { |option| option.votes.count } %>
  <% poll.poll_options.each do |option| %>
    <li class="list-group-item">
      <%= option.title %>
      <%= button_to 'Vote', event_poll_poll_option_votes_path(@event, poll, option), method: :post, data: { turbo_method: :post }, class: 'btn btn-primary btn-sm' %>
      <% vote_count = option.votes.count %>
      <% percentage = total_votes.zero? ? 0 : (vote_count.to_f / total_votes * 100).round %>
      <div class="progress mt-2">
        <div class="progress-bar custom-progress-bar" role="progressbar" style="width: <%= percentage %>%;" aria-valuenow="<%= percentage %>" aria-valuemin="0" aria-valuemax="100">
          <%= percentage %>%
        </div>
      </div>
      <span class="badge bg-secondary"><%= option.votes.count %> votes</span>
      <%= link_to 'Edit', edit_event_poll_poll_option_path(@event, poll, option), class: 'btn btn-warning btn-sm' %>
      <%= link_to 'Delete', event_poll_poll_option_path(@event, poll, option), method: :delete, data: { turbo_method: :delete, confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
    </li>
  <% end %>
</ul>