config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root 'home#index'

  resources :events do
    member do
      post 'invite'
      get 'join'
      get 'details'
      get 'invite'
      get 'polls'
      get 'comments'
      get 'announcements'
    end
    resources :polls, only: [:create, :destroy] do
      resources :poll_options, only: [:new, :create, :edit, :update, :destroy] do
        resources :votes, only: [:create, :destroy]
      end
    end
    resources :comments, only: [:create, :update] do
      member do
        patch 'pin'
      end
    end
  end

  resources :users, only: [:show]
end

app/models/poll.rb
class Poll < ApplicationRecord
  belongs_to :event
  has_many :poll_options, dependent: :destroy
  has_many :votes, through: :poll_options, dependent: :destroy

  accepts_nested_attributes_for :poll_options, allow_destroy: true
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event
  before_action :authorize_user!

  def create
    @poll = @event.polls.build(poll_params)
    if @poll.save
      redirect_to @event, notice: 'Poll was successfully created.'
    else
      redirect_to @event, alert: 'There was an error creating the poll.'
    end
  end

  def destroy
    @poll = @event.polls.find(params[:id])
    @poll.destroy
    redirect_to @event, notice: 'Poll was successfully deleted.'
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def authorize_user!
    unless @event.creator == current_user || @event.attendees.exists?(id: current_user.id)
      redirect_to root_path, alert: 'You are not authorized to perform this action.'
    end
  end

  def poll_params
    params.require(:poll).permit(:title, poll_options_attributes: [:id, :title, :_destroy])
  end
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/polls/_form.html.erb
<%= form_with(model: [ @poll.event, @poll ], local: true) do |form| %>
  <% if @poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll.errors.count, "error") %> prohibited this poll from being saved:</h2>
      <ul>
        <% @poll.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div id="poll-options">
    <%= form.fields_for :poll_options do |poll_option_fields| %>
      <div class="field">
        <%= poll_option_fields.label :title %>
        <%= poll_option_fields.text_field :title %>
        <%= link_to 'Remove', '#', class: 'remove_poll_option' %>
      </div>
    <% end %>
  </div>
  <%= link_to 'Add Option', '#', id: 'add_poll_option' %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/polls/_poll.html.erb
<div id="<%= dom_id poll %>">
  <h3><%= poll.title %></h3>
  
  <ul>
    <% poll.votes.each do |vote| %>
      <li><%= vote.status %> by <%= vote.user.email %></li>
    <% end %>
  </ul>

  <h4>Add Vote</h4>
  <%= form_with(model: [poll, poll.votes.build], local: true) do |form| %>
    <div class="field">
      <%= form.label :status %>
      <%= form.select :status, ['In', 'Out'] %>
    </div>

    <div class="actions">
      <%= form.submit 'Vote' %>
    </div>
  <% end %>
</div>

app/views/polls/_poll_fields.html.erb
<div class="nested-fields">
  <%= f.label :title, 'Poll Title', class: 'form-label' %>
  <%= f.text_field :title, class: 'form-control' %>

  <h4>Poll Options</h4>
  <%= f.fields_for :poll_options do |option_form| %>
    <div class="nested-fields">
      <%= option_form.label :option, 'Poll Option', class: 'form-label' %>
      <%= option_form.text_field :option, class: 'form-control' %>
      <%= option_form.check_box :_destroy %>
      <%= option_form.label :_destroy, 'Remove', class: 'form-check-label' %>
    </div>
  <% end %>
  <%= link_to_add_fields "Add Poll Option", f, :poll_options %>
</div>

app/views/polls/_poll_option_fields.html.erb
<div class="nested-fields">
  <%= f.label :option, 'Poll Option', class: 'form-label' %>
  <%= f.text_field :option, class: 'form-control' %>
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, 'Remove', class: 'form-check-label' %>
</div>

app/views/polls/edit.html.erb
<h1>Edit Poll</h1>
<%= render 'form', poll: @poll %>
<%= link_to 'Back', event_polls_path(@event) %>

app/views/polls/index.html.erb
<h1>Polls</h1>
<%= link_to 'New Poll', new_event_poll_path(@event), class: 'btn btn-primary' %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @polls.each do |poll| %>
      <tr>
        <td><%= poll.title %></td>
        <td>
          <%= link_to 'Show', [@poll.event, poll], class: 'btn btn-primary' %>
          <%= link_to 'Edit', edit_event_poll_path(@poll.event, poll), class: 'btn btn-secondary' %>
          <%= link_to 'Destroy', [@poll.event, poll], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/polls/new.html.erb
<h1>New Poll</h1>
<%= render 'form', poll: @poll %>
<%= link_to 'Back', event_polls_path(@event) %>

app/views/polls/show.html.erb
<h1><%= @poll.title %></h1>

<h2>Options</h2>
<%= form_with(url: vote_event_poll_path(@event, @poll), local: true) do |form| %>
  <% @poll.poll_options.each do |option| %>
    <div>
      <%= form.radio_button :poll_option_id, option.id %>
      <%= option.title %> - <%= option.votes_count %> votes
    </div>
  <% end %>
  <%= form.submit 'Vote' %>
<% end %>